---
services:
  traefik:
    networks:
      opencloud-net:
        aliases:
          - ${COLLABORA_DOMAIN:-collabora.opencloud.test}
  collabora:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.collabora.entrypoints=https"
      - "traefik.http.routers.collabora.rule=Host(`${COLLABORA_DOMAIN:-collabora.opencloud.test}`)"
      - "traefik.http.routers.collabora.${TRAEFIK_SERVICES_TLS_CONFIG}"
      - "traefik.http.routers.collabora.service=collabora"
      - "traefik.http.routers.collabora.middlewares=hsts-header"
      - "traefik.http.services.collabora.loadbalancer.server.port=9980"
